### ISSUE TITLE
Change all-contributors badge to new automatic shields.io badge

### ISSUE THREAD

**Issue by nils-a** [WormieCorp/generator-cake-addin#456]
**Describe the bug**
all-contributors-badge does not update automatically in a generated README.md when using all-contributors (bot or cli)

**To Reproduce**
1. Generate a new addin & choose to use all-contributors
2. add a contributor by using the bot or the cli

* The contributor is listed in the table of contributors
* The all-contributors badge is not updated.

**Expected behavior**
The all-contributors badge should be updated.

**Additional context**
The problem seems to be missing star- and end-tags. See https://allcontributors.org/docs/en/bot/faq

(However, adding those seems to break the flow of badges..)

**Comment by AdmiringWorm** [comment]
Thanks for reporting this issue, the missing start and end tag is honestly something I have forgotten to add.

Not sure how to resolve that it breaks the flow of badges though, but I will test out a few things to see if it works.

**Comment by AdmiringWorm** [comment]
@nils-a Since a badge is officially part of the shields.io website now, there is no need to have all-contributors bot updating the badge anymore.

Replace the content of your Readme.md badge with the following (remove the comments as well):
```
![All Contributors](https://img.shields.io/github/all-contributors/ORGANIZATION/REPOSITORY_NAME?color=orange&style=flat-square)
```

I will update the generator with these changes

**Comment by AdmiringWorm** [comment]
@all-contributors please add @nils-a for ideas
